name: Add Target Branch to Pull Request Title
on: pull_request
jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      if: github.event.action == 'opened'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '.*'
        title-template: '[%basebranch%]'
        replace-title: false
        title-prefix-space: true
        uppercase-title: false
