name: Add Target Branch to Pull Request Title
on: pull_request
jobs:
  pr_update_text:
    runs-on: ubuntu-latest
    steps:
    - uses: joel-zilliqa/pr-update-action@v1.0.10
      if: github.event.action == 'opened'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        use-base-branch: true
        branch-regex: '.*'
        title-template: '[%branch%]'
        replace-title: false
        title-prefix-space: true
        uppercase-title: false
